App_login/urls.py
from django.urls import path
from App_login import views
app_name='App_login'

urlpatterns = [
    path('signup/',views.sign_up,name='signup'),
    path('login/',views.login_page,name='login'),
    path('edit/',views.edit_profile,name='edit'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.Profile,name='profile'),
    path('user/<username>/',views.user,name='user'),
    path('follow/<username>/',views.follow,name='follow'),
    path('unfollow/<username>/',views.unfollow,name='unfollow'),

]

Django-social-media-page-master/App_login/urls.py
from django.urls import path
from App_login import views
app_name='App_login'

urlpatterns = [
    path('signup/',views.sign_up,name='signup'),
    path('login/',views.login_page,name='login'),
    path('edit/',views.edit_profile,name='edit'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.Profile,name='profile'),
    path('user/<username>/',views.user,name='user'),
    path('follow/<username>/',views.follow,name='follow'),
    path('unfollow/<username>/',views.unfollow,name='unfollow'),

]

Django-social-media-page-master/App_posts/urls.py
from django.urls import path
from App_posts import views
app_name='App_posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('liked/<pk>/',views.liked,name='liked'),
    path('unlike/<pk>/',views.unlike,name='unlike'),


]

Social_Media_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from App_posts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('App_login.urls')),
    path('posts/',include('App_posts.urls')),
    path('',views.home,name='home'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    full_name = models.CharField(max_length=264, blank=True)
    Profile_pic = models.ImageField(upload_to='pro_ pic', blank=True)
    description = models.TextField( blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)

Django-social-media-page-master/App_login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    full_name = models.CharField(max_length=264, blank=True)
    Profile_pic = models.ImageField(upload_to='pro_ pic', blank=True)
    description = models.TextField( blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)

Django-social-media-page-master/App_posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE ,related_name='post' )
    image=models.ImageField(upload_to='post_images')
    caption=models.CharField(max_length=264,blank=True)
    upload_time=models.DateTimeField(auto_now_add=True)
    update_time=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-update_time']


class Like(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='Liked_post')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='liker')
    created_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}:{}'.format(self.user,self.post)

App_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile

class CreateNewUser(UserCreationForm):

    Email=forms.EmailField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username=forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'username'}))
    password1=forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'password'}))
    password2=forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'confirm password'}))



    class Meta:
        model=User
        fields=('Email','username','password1','password2')

class Edit_ProfileForm(forms.ModelForm):
    dob=forms.CharField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = UserProfile
        exclude = ('user',)

Django-social-media-page-master/App_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile

class CreateNewUser(UserCreationForm):

    Email=forms.EmailField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username=forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'username'}))
    password1=forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'password'}))
    password2=forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'confirm password'}))



    class Meta:
        model=User
        fields=('Email','username','password1','password2')

class Edit_ProfileForm(forms.ModelForm):
    dob=forms.CharField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = UserProfile
        exclude = ('user',)

Django-social-media-page-master/App_posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model=Post
        fields=['image','caption',]

App_login/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import CreateNewUser, Edit_ProfileForm
from django.contrib.auth import logout, login, authenticate
from django.urls import reverse, reverse_lazy
from .models import UserProfile, Follow
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from App_posts.forms import PostForm
from django.contrib.auth.models import User


# Create your views here.

def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
            return HttpResponseRedirect(reverse('App_login:login'))

    return render(request, 'App_login/sign_up.html', context={'title': 'signup.Instagram', 'form': form})


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_posts:home'))
    return render(request, 'App_login/login.html', context={'title': 'login', 'form': form})


@login_required
def edit_profile(request):
    current_user = UserProfile(user=request.user)
    form = Edit_ProfileForm(instance=current_user)
    if request.method == 'POST':
        form = Edit_ProfileForm(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = Edit_ProfileForm(instance=current_user)
            return HttpResponseRedirect(reverse('App_login:profile'))
    return render(request, 'App_login/profile.html', context={'title': 'profile.social', 'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_login:login'))


@login_required
def Profile(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'App_login/user.html', context={'form': form})


@login_required
def user(request, username):
    user_other = User.objects.get(username=username)
    #already_followed = Follow.objects.filter(follower=request.user, following=request.user)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('App_login:profile'))

    return render(request, 'App_login/user_others.html',
                  context={'user_other': user_other,})


@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_followed:
        followed_user=Follow(follower=follower_user, following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('App_login:user', kwargs={'username': username}))


@login_required
def unfollow(request, username):
    following_user= User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('App_login:user', kwargs={'username': username}))

Django-social-media-page-master/App_login/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import CreateNewUser, Edit_ProfileForm
from django.contrib.auth import logout, login, authenticate
from django.urls import reverse, reverse_lazy
from .models import UserProfile, Follow
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from App_posts.forms import PostForm
from django.contrib.auth.models import User


# Create your views here.

def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
            return HttpResponseRedirect(reverse('App_login:login'))

    return render(request, 'App_login/sign_up.html', context={'title': 'signup.Instagram', 'form': form})


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_posts:home'))
    return render(request, 'App_login/login.html', context={'title': 'login', 'form': form})


@login_required
def edit_profile(request):
    current_user = UserProfile(user=request.user)
    form = Edit_ProfileForm(instance=current_user)
    if request.method == 'POST':
        form = Edit_ProfileForm(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = Edit_ProfileForm(instance=current_user)
            return HttpResponseRedirect(reverse('App_login:profile'))
    return render(request, 'App_login/profile.html', context={'title': 'profile.social', 'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_login:login'))


@login_required
def Profile(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'App_login/user.html', context={'form': form})


@login_required
def user(request, username):
    user_other = User.objects.get(username=username)
    #already_followed = Follow.objects.filter(follower=request.user, following=request.user)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('App_login:profile'))

    return render(request, 'App_login/user_others.html',
                  context={'user_other': user_other,})


@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_followed:
        followed_user=Follow(follower=follower_user, following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('App_login:user', kwargs={'username': username}))


@login_required
def unfollow(request, username):
    following_user= User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('App_login:user', kwargs={'username': username}))

Django-social-media-page-master/App_posts/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Post,Like
from App_login.models import Follow
from django.contrib.auth.models import User


# Create your views here.
@login_required
def home(request):
    following_list = Follow.objects.filter(follower=request.user)
    posts=Post.objects.filter(author__in=following_list.values_list('following'))
    liked_post=Like.objects.filter(user=request.user)
    liked_post_list=liked_post.values_list('post',flat=True)
   # print(liked_post_list)
    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = User.objects.filter(username__icontains=search)
    return render(request, 'App_posts/home.html',
                  context={'title': 'home page', 'search': search, 'result': result,'posts':posts,})

@login_required
def liked(request,pk):
    post=Post.objects.get(pk=pk,user=request.user)
    already_liked=Like.objects.filter(post=post,user=request.user)
    if not already_liked:
        liked_post=Like(post=post,user=request.user)
        liked_post.save()
    return HttpResponseRedirect(reverse('home'))

@login_required
def unlike(request,pk):
    post=Post.objects.get(pk=pk,user=request.user)
    already_liked=Like.objects.filter(post=post,user=request.user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('home'))

Django-social-media-page-master/templates/App_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} {% endblock %}
{% block css %}
<style>
       .login{
        width:550px;
        border:1px solid #ccc;
        padding:25px;
    }
    .sign_up{
        width:550px;
        border:1px solid #ccc;
        padding:10px;
    }
</style>
{% endblock %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <center>
    <div class="login">
        {{ form|crispy }}
        <button type="submit"  class="btn btn-primary" style="width:100%">Login</button>
    </div>
    <br>
        <div class="sign_up">
             <p>Don't Have any account?<a href="{% url 'App_login:signup' %}">Sign_up</a></p>
        </div>

    </center>
</form>

{% endblock %}

Django-social-media-page-master/templates/App_login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title %} {{title}} {% endblock %}
{% block css %}
{% endblock %}
{% block body %}
<form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

Django-social-media-page-master/templates/App_login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} {{title}} {% endblock %}
{% block css %}
<style >
    .sign_up{
    width:550px;
    border:1px solid #ccc;
    padding:25px;
    }
    .login{
    width:550px;
    border:1px solid #ccc;
    padding:15px;
    }

</style>
{% endblock %}

{% block body %}
{% csrf_token %}
<center>
    <h3>Sign up to see photos from your </br>friends </h3>
    <div class="sign_up">
    <form method="POST">
        {% csrf_token %}
    {{ form|crispy }}
    <button type="submit"  name="submit" class="btn btn-primary" style="width:100%">Sign Up</button>
</form>
</div>
    <br>
    <div class="login">
        <p>Have an account? <a href="{% url 'App_login:login' %}">Login</a></p>
    </div>
</center>
{% endblock %}

Django-social-media-page-master/templates/App_login/user.html
{% extends 'navbar.html' %}
{% block title %}
{{user.user_profile.full_name}} (@{{ user.username}})
{% endblock %}
{% block css %}
<style>
    .crop{
    width:200px;
    height:400px;
    overflow:hidden;
}
    .crop img {
    width:400px;
    height:300px;
    margin:-75px 0 0 -100px;

    }

</style>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-4">
        {% if user.user_profile.Profile_pic %}
            <img src="/media/{{user.user_profile.Profile_pic}}" width="250px" height="250px" class="rounded-circle">
        {% else %}
            <img src="/media/default.png" width="250px" height="250px" class="rounded-circle">
        {% endif %}
    </div>
    <div class="col-sm-8">
       <h2>{{user.username}} &nbsp; <a href="{% url 'App_login:edit' %}" class="btn btn-success">Edit Profile</a></h2>
       <br>
        <h4>{{ user.post.count}}Posts &nbsp; &nbsp;{{user.following.count}}Follower &nbsp;{{user.follower.count}}Following </h4>
        <br>
        <h3>{{user.user_profile.full_name}}</h3>
        <br>
        <h5>{{user.user_profile.description|linebreaks}}</h5>

    </div>
    </div>
    <hr>
   <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  New Post
</button>
<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Create a Post</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form method="POST" enctype="multipart/form-data">
            {{form.as_p}}
            {% csrf_token %}
            <button type="submit">Post</button>
        </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>
<br>
<br>
<div class="row">
    {% for post in user.post.all %}
    <div class="crop">
    <img src="/media/{{post.image}}" title="{{post.caption}}">
        </div>
    {% endfor %}
</div>


{% endblock %}

Django-social-media-page-master/templates/App_login/user_others.html
{% extends 'navbar.html' %}
{% block title %}
{{user_other.user_profile.full_name}} (@{{ user_other.username}})
{% endblock %}
{% block css %}
<style>
    .crop{
    width:200px;
    height:400px;
    overflow:hidden;
}
    .crop img {
    width:400px;
    height:300px;
    margin:-75px 0 0 -100px;

    }

</style>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-4">
        {% if user_other.user_profile.Profile_pic %}
            <img src="/media/{{user_other.user_profile.Profile_pic}}" width="250px" height="250px" class="rounded-circle">
        {% else %}
            <img src="/media/default.png" width="250px" height="250px" class="rounded-circle">
        {% endif %}
    </div>
    <div class="col-sm-4">
        <h1>{{user_other.username}} &nbsp;
            {% if not already_followed %}
            <a href="{% url 'App_login:follow' username=user_other.username %}" class="btn btn-success">Follow</a>
            {% else %}
            <a href="{% url 'App_login:unfollow' username=user_other.username %}" class="btn btn-success">Unfollow</a>
            {% endif %}
        </h1>


        <h5>{{ user_other.post.count}}Posts &nbsp; &nbsp;{{user_other.following.count}}Follower &nbsp;{{user_other.follower.count}}Following </h5>
        <br>
           <h3> {{use_other.user_profile.full_name}}</h3>
        <br>

        <p>{{use_other.user_profile.description|linebreaks}}</p>

    </div>
    </div>
    <hr>
<br>
<br>
<div class="row">
    {% for post in user_other.post.all %}
    <div class="crop">
    <img src="/media/{{post.image}}" title="{{post.caption}}">
        </div>
    {% endfor %}
</div>


{% endblock %}