App_login/urls.py
from django.urls import path
from App_login import views
app_name='App_login'

urlpatterns = [
    path('signup/',views.sign_up,name='signup'),
    path('login/',views.login_page,name='login'),
    path('edit/',views.edit_profile,name='edit'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.Profile,name='profile'),
    path('user/<username>/',views.user,name='user'),
    path('follow/<username>/',views.follow,name='follow'),
    path('unfollow/<username>/',views.unfollow,name='unfollow'),

]

App_posts/urls.py
from django.urls import path
from App_posts import views
app_name='App_posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('liked/<pk>/',views.liked,name='liked'),
    path('unlike/<pk>/',views.unlike,name='unlike'),


]

Django-social-media-page-master/App_posts/urls.py
from django.urls import path
from App_posts import views
app_name='App_posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('liked/<pk>/',views.liked,name='liked'),
    path('unlike/<pk>/',views.unlike,name='unlike'),


]

Social_Media_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from App_posts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('App_login.urls')),
    path('posts/',include('App_posts.urls')),
    path('',views.home,name='home'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE ,related_name='post' )
    image=models.ImageField(upload_to='post_images')
    caption=models.CharField(max_length=264,blank=True)
    upload_time=models.DateTimeField(auto_now_add=True)
    update_time=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-update_time']


class Like(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='Liked_post')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='liker')
    created_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}:{}'.format(self.user,self.post)

Django-social-media-page-master/App_posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE ,related_name='post' )
    image=models.ImageField(upload_to='post_images')
    caption=models.CharField(max_length=264,blank=True)
    upload_time=models.DateTimeField(auto_now_add=True)
    update_time=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-update_time']


class Like(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='Liked_post')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='liker')
    created_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}:{}'.format(self.user,self.post)

App_posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model=Post
        fields=['image','caption',]

Django-social-media-page-master/App_posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model=Post
        fields=['image','caption',]

App_posts/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Post,Like
from App_login.models import Follow
from django.contrib.auth.models import User


# Create your views here.
@login_required
def home(request):
    following_list = Follow.objects.filter(follower=request.user)
    posts=Post.objects.filter(author__in=following_list.values_list('following'))
    liked_post=Like.objects.filter(user=request.user)
    liked_post_list=liked_post.values_list('post',flat=True)
   # print(liked_post_list)
    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = User.objects.filter(username__icontains=search)
    return render(request, 'App_posts/home.html',
                  context={'title': 'home page', 'search': search, 'result': result,'posts':posts,})

@login_required
def liked(request,pk):
    post=Post.objects.get(pk=pk,user=request.user)
    already_liked=Like.objects.filter(post=post,user=request.user)
    if not already_liked:
        liked_post=Like(post=post,user=request.user)
        liked_post.save()
    return HttpResponseRedirect(reverse('home'))

@login_required
def unlike(request,pk):
    post=Post.objects.get(pk=pk,user=request.user)
    already_liked=Like.objects.filter(post=post,user=request.user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('home'))

Django-social-media-page-master/App_posts/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Post,Like
from App_login.models import Follow
from django.contrib.auth.models import User


# Create your views here.
@login_required
def home(request):
    following_list = Follow.objects.filter(follower=request.user)
    posts=Post.objects.filter(author__in=following_list.values_list('following'))
    liked_post=Like.objects.filter(user=request.user)
    liked_post_list=liked_post.values_list('post',flat=True)
   # print(liked_post_list)
    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = User.objects.filter(username__icontains=search)
    return render(request, 'App_posts/home.html',
                  context={'title': 'home page', 'search': search, 'result': result,'posts':posts,})

@login_required
def liked(request,pk):
    post=Post.objects.get(pk=pk,user=request.user)
    already_liked=Like.objects.filter(post=post,user=request.user)
    if not already_liked:
        liked_post=Like(post=post,user=request.user)
        liked_post.save()
    return HttpResponseRedirect(reverse('home'))

@login_required
def unlike(request,pk):
    post=Post.objects.get(pk=pk,user=request.user)
    already_liked=Like.objects.filter(post=post,user=request.user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('home'))

templates/App_posts/home.html
{% extends 'navbar.html' %}
{% block title %} {{title}}{% endblock %}
{% block body%}
{% if search %}
{% for user in result %}
<div class="row">
    <div class="col-sm-2">
        {% if user.user_profile.Profile_pic %}
        <img src="/media/{{user.user_profile.Profile_pic}}" width="75px" height="75px" class="rounded-circle">

        {% else %}
        <img src="/media/default.png" width="75px" height="75px" class="rounded-circle">
        {% endif %}

    </div>
    <div class="col-sm-10">
        <a href="{% url 'App_login:user' username=user.username %}">{{user.username}}</a>
        <br>
        {{user.user_profile.full_name}}
    </div>
</div>
<br>
{% endfor %}
{% else %}
<div class="row">
    <div class="col-sm-8">

{% for post in posts %}
<div style="border: 1px solid #88888;">
    <div style="padding:10px">
        {% if post.author.user_profile.Profile_pic %}
            <img src="/media/{{user.user_profile.Profile_pic}}" width="40px" height="40px" class="rounded-circle">
        {% else %}
            <img src="/media/default.png" width="40px" height="40px" class="rounded-circle">
        {% endif %}
         <a href="{% url 'App_login:user' username=post.author %">{{post.author}}</a>
    </div>

    <img src="/media/{{post.image}}" width="100%">
    <div style="padding:20px">
        {{post.caption}}<br>
        {{post.liked_post.count}}<br>
        {% if post.pk in liked_post_list %}
        <a herf="{% url 'App_posts:unliked' pk=post.pk %}"><i class="fa fa-heart" style="font-size-36px"></i></a>
        {% else %}
        <a herf="{% url 'App_posts:liked' pk=post.pk %}"><i class="fa fa-heart" style="font-size-36px"></i></a>
        {% endif %}
    </div>
</div>
<br>
<br>
{% endfor %}

    </div>
    <div class="col-sm-4">
        <div class="row">
            <div class="col-sm-4">
                 {% if user.user_profile.Profile_pic %}
                    <img src="/media/{{user.user_profile.Profile_pic}}" width="75px" height="75px" class="rounded-circle">
                 {% else %}
                    <img src="/media/default.png" width="75px" height="75px" class="rounded-circle">
                {% endif %}
                <div class="col-sm-8">
                    {{user.username}}
                    <br>
                    {{user.user_profile.full_name}}
                </div>

            </div>

        </div>

    </div>

</div>
{% for author in following_list %}
{% for post in author.following.Post.all %}
<div style="border: 1px solid #88888;">
    <div style="padding:10px">
        {% if post.author.user_profile.Profile_pic %}
            <img src="/media/{{user.user_profile.Profile_pic}}" width="40px" height="40px" class="rounded-circle">
        {% else %}
            <img src="/media/default.png" width="40px" height="40px" class="rounded-circle">
        {% endif %}
         <a href="{% url 'App_login:user' username=post.author %">{{post.author}}</a>
    </div>
    <img src="/media/{{post.image}}" width="100%">
</div>
<br>
<br>
{% endfor %}
{% endfor %}
{% endif %}
{% endblock %}